repos:
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        name: Format Package

  - repo: local
    hooks:
      - id: flake8
        entry: .pre-commit-hooks/flake8.sh
        name: Lint Package
        language: script
        types: [python]
        always_run: true
        pass_filenames: false

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
        name: Propagate Third-Party Packages

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4
    hooks:
      - id: isort
        name: Sort Package Imports

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.790
    hooks:
      - id: mypy
        name: Typecheck Package
