# Stubs for file_config (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from . import __version__ as __version__, contrib as contrib, handlers as handlers
from ._file_config import config as config, from_dict as from_dict, make_config as make_config, to_dict as to_dict, validate as validate, var as var
from .constants import CONFIG_KEY as CONFIG_KEY
from .schema_builder import Regex as Regex, build_schema as build_schema
