# Stubs for file_config.__version__ (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

__name__: str
__repo__: str
__version__: str
__description__: str
__author__: str
__contact__: str
__license__: str
