steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
    displayName: Use Python 3.7

  - template: install-dependencies.yml

  - script: python -m pip install pipenv --upgrade
    displayName: Install Pipenv

  - script: pipenv install --dev --pre --system --skip-lock
    displayName: Create Development Environment

  - script: |
      pipenv run inv -e clean
      pipenv run inv -e docs.build-news -y
      pipenv run inv -e build
    displayName: Build Package

  - task: CopyFiles@2
    inputs:
      sourceFolder: dist/
      contents: "**"
      targetFolder: $(Build.ArtifactStagingDirectory)
    displayName: Copy Artifacts

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)
      artifactName: PackageArtifacts
    displayName: Publish Artifacts
