steps:
  - script: coverage xml -o coverage.xml
    displayName: Build Coverage Report

  - script: python-codacy-coverage -r coverage.xml
    env:
      CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)
    displayName: Send Coverage Report
