steps:
  - script: python -m pip install codacy-coverage codecov
    displayName: Install Coverage Reporters

  - script: coverage xml -o coverage.xml
    displayName: Build Coverage Report

  - script: |
      python-codacy-coverage -r coverage.xml
      codecov
    env:
      CODACY_PROJECT_TOKEN: $(CODACY_PROJECT_TOKEN)
      CODECOV_TOKEN: $(CODECOV_TOKEN)
    displayName: Send Coverage Report
