# Stubs for file_config.handlers (Python 3)
#
# NOTE: This dynamically typed stub was automatically generated by stubgen.

from .ini import INIHandler as INIHandler
from .json import JSONHandler as JSONHandler
from .msgpack import MsgpackHandler as MsgpackHandler
from .pickle import PickleHandler as PickleHandler
from .toml import TOMLHandler as TOMLHandler
from .xml import XMLHandler as XMLHandler
from .yaml import YAMLHandler as YAMLHandler
